### ISSUE TITLE
The latest version of PHP, lots of warnings!

### ISSUE THREAD

**Issue by mizunago** [hokkaidoperson/DokuWiki-AccsCounter-Plugin#21]
I am using bitnami's docker version dokuwiki.
I recently raised the dokuwiki version and php version, and now I have the following problem.

dokuwiki version: Release 2023-04-04 "Jack Jackrum"
php_version: 8.1.18

The following warnings are output in large quantities and soon fill up the disk with logs
Line numbers and errors vary slightly, so not all are listed here, but they can be provided!

私は bitnami の docker 版の dokuwiki を使用しています。
最近、dokuwiki と php のバージョンを更新したところ（docker-compose pull）、以下のような問題が発生するようになりました

以下の警告が大量に出力され、すぐにログでディスクがいっぱいになってしまいます。
行番号やエラーは若干異なるため、ここにすべて記載しているわけではありませんが、提供することは可能です

```
2023-05-02 19:17:20     /bitnami/dokuwiki/lib/plugins/accscounter/syntax/counter.php(179)       E_WARNING: Undefined array key 1
  #0 /bitnami/dokuwiki/lib/plugins/accscounter/syntax/counter.php(179): dokuwiki\ErrorHandler::errorHandler()
  #1 /bitnami/dokuwiki/lib/plugins/accscounter/syntax/counter.php(361): syntax_plugin_accscounter_counter->plugin_counter_get_count()
  #2 /opt/bitnami/dokuwiki/inc/parser/renderer.php(119): syntax_plugin_accscounter_counter->render()
  #3 /opt/bitnami/dokuwiki/inc/parserutils.php(700): Doku_Renderer->plugin()
  #4 /opt/bitnami/dokuwiki/inc/parserutils.php(158): p_render()
  #5 /opt/bitnami/dokuwiki/inc/parserutils.php(96): p_cached_output()
  #6 /opt/bitnami/dokuwiki/inc/template.php(1592): p_wiki_xhtml()
  #7 /bitnami/dokuwiki/lib/tpl/mindthedark/main.php(81): tpl_include_page()
  #8 /opt/bitnami/dokuwiki/inc/actions.php(27): include('...')
  #9 /opt/bitnami/dokuwiki/doku.php(126): act_dispatch()
  #10 {main}
2023-05-02 19:17:20     /bitnami/dokuwiki/lib/plugins/accscounter/syntax/counter.php(343)       E_WARNING: Constant CURRENT already defined
  #0 [internal function]: dokuwiki\ErrorHandler::errorHandler()
  #1 /bitnami/dokuwiki/lib/plugins/accscounter/syntax/counter.php(343): define()
  #2 /opt/bitnami/dokuwiki/inc/parser/renderer.php(119): syntax_plugin_accscounter_counter->render()
  #3 /opt/bitnami/dokuwiki/inc/parserutils.php(700): Doku_Renderer->plugin()
  #4 /opt/bitnami/dokuwiki/inc/parserutils.php(158): p_render()
  #5 /opt/bitnami/dokuwiki/inc/parserutils.php(96): p_cached_output()
  #6 /opt/bitnami/dokuwiki/inc/template.php(1592): p_wiki_xhtml()
  #7 /bitnami/dokuwiki/lib/tpl/mindthedark/main.php(81): tpl_include_page()
  #8 /opt/bitnami/dokuwiki/inc/actions.php(27): include('...')
  #9 /opt/bitnami/dokuwiki/doku.php(126): act_dispatch()
  #10 {main}
2023-05-02 19:17:20     /bitnami/dokuwiki/lib/plugins/accscounter/syntax/popularity.php(103)    E_WARNING: Undefined array key 0
  #0 /bitnami/dokuwiki/lib/plugins/accscounter/syntax/popularity.php(103): dokuwiki\ErrorHandler::errorHandler()
  #1 /opt/bitnami/dokuwiki/inc/parser/renderer.php(119): syntax_plugin_accscounter_popularity->render()
  #2 /opt/bitnami/dokuwiki/inc/parserutils.php(700): Doku_Renderer->plugin()
  #3 /opt/bitnami/dokuwiki/inc/parserutils.php(158): p_render()
  #4 /opt/bitnami/dokuwiki/inc/parserutils.php(96): p_cached_output()
  #5 /opt/bitnami/dokuwiki/inc/template.php(1592): p_wiki_xhtml()
  #6 /bitnami/dokuwiki/lib/tpl/mindthedark/main.php(81): tpl_include_page()
  #7 /opt/bitnami/dokuwiki/inc/actions.php(27): include('...')
  #8 /opt/bitnami/dokuwiki/doku.php(126): act_dispatch()
  #9 {main}

```

**Comment by mizunago** [comment]
The following site settings can alleviate the problem of logs overwhelming the disk
Note, however, that this is a temporary solution, as other error logs will not be logged.

以下のサイト設定で、ログがディスクを圧迫してしまう問題については軽減が可能です
ただし、他の重大なエラーログまで記録されなくなってしまうため、一時的な対策であることに注意してください

```
dontlog
  Disable logging for these types of logs.

  Check the "error" box.
```
